version: '2'

services:
    mongo:
        image: mongo:latest
        ports:
        - '27017:27017'
    servicio-iehr :
        container_name : test-tec-iehr
        build : .
        ports :
            - "8080:8080"
        links : 
            - mongo
